import setuptools

setuptools.setup(
    name="pare",
    version="0.1",
    author="PARE team",
    description="PARE: Part Attention Regressor for 3D Human Body Estimation",
    packages=setuptools.find_packages(),
    python_requires='>=3.6',
    install_requires=
    ["numpy",
     "torch",
     "torchvision",
     "joblib",
     "opencv-python",
     "trimesh",
     "pyrender",
     "smplx",
     "tqdm",
     "loguru",
     "albumentations",
     "scipy",
     "pyyaml",
     "yacs",
     "matplotlib",
     "scikit-image",
     "pillow",
     "pytorch-lightning",
     "numba",
     "filterpy",
     "flatten-dict",
     "fastai",
     "jpeg4py",
     "chumpy",
     "torchgeometry",
     "yolov3 @ git+https://github.com/mkocabas/yolov3-pytorch.git",
     "multi_person_tracker @ git+https://github.com/mkocabas/multi-person-tracker.git",
     "pytube @ git+https://github.com/giacaglia/pytube.git", ]
)
